**The following code is implmentation of the idea from the paper (http://arxiv.org/pdf/1609.04938v1.pdf)
Im2Latex
A general-purpose, deep learning-based system to decompile an image into presentational markup. For example, we can infer the LaTeX or HTML source from a rendered image.**

The basic preprocessing is done similar to the paper.
Used the following code from the repo https://github.com/harvardnlp/im2markup
https://github.com/harvardnlp/im2markup/tree/master/scripts/preprocessing
1)preprocess_formulas.py --> preprocessed formulas  and obtained formulas.norm.lst
2)preprocess_filter.py --> With this script obtained train.lst, test.lst, valid.lst (These files contain the image names and the corresponding formulae indexes
3)preprocess_latex.js --> preprocessed latex formulas
4)generate_latex_vocab.py --> generates required vocab and some important dictionaries files used for further preprocessing

In [1]:
vocab = open('../input/taskset/latex_vocab.txt').read().split('\n')
vocab_to_idx = dict([ (vocab[i],i) for i in range(len(vocab))])
formulas = open('../input/taskset/formulas.norm.lst').read().split('\n')

In [2]:
idx_to_vocab = dict([ (i,vocab[i]) for i in range(len(vocab))])

Printing the Dictionaries

In [3]:
vocab_to_idx #vocab dict

{'!': 0,
 '"': 1,
 '&': 2,
 "'": 3,
 '(': 4,
 ')': 5,
 '*': 6,
 '+': 7,
 ',': 8,
 '-': 9,
 '--': 10,
 '---': 11,
 '.': 12,
 '/': 13,
 '0': 14,
 '0.1': 15,
 '0.14': 16,
 '0.3': 17,
 '0.4': 18,
 '0.5': 19,
 '1': 20,
 '2': 21,
 '3': 22,
 '3.1': 23,
 '3.2': 24,
 '4': 25,
 '5': 26,
 '6': 27,
 '7': 28,
 '8': 29,
 '8.5': 30,
 '9': 31,
 ':': 32,
 ';': 33,
 '<': 34,
 '=': 35,
 '>': 36,
 '?': 37,
 '@': 38,
 'A': 39,
 'B': 40,
 'C': 41,
 'D': 42,
 'E': 43,
 'F': 44,
 'G': 45,
 'H': 46,
 'I': 47,
 'J': 48,
 'K': 49,
 'L': 50,
 'M': 51,
 'N': 52,
 'O': 53,
 'Object]': 54,
 'P': 55,
 'Q': 56,
 'R': 57,
 'S': 58,
 'T': 59,
 'U': 60,
 'V': 61,
 'W': 62,
 'X': 63,
 'Y': 64,
 'Z': 65,
 '[': 66,
 '[object': 67,
 '\\': 68,
 '\\!': 69,
 '\\#': 70,
 '\\&': 71,
 "\\'": 72,
 '\\*': 73,
 '\\,': 74,
 '\\-': 75,
 '\\/': 76,
 '\\:': 77,
 '\\;': 78,
 '\\AA': 79,
 '\\Big': 80,
 '\\Bigg': 81,
 '\\Biggl': 82,
 '\\Biggm': 83,
 '\\Biggr': 84,
 '\\Bigl': 85,
 '\\Bigm': 86,
 '\\Bigr': 87,
 '\\Delta': 88,
 '\\Downarrow': 

In [4]:
lab=idx_to_vocab.keys()
print(lab)

dict_keys([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219,

In [5]:
def formula_to_indices(formula):
    formula = formula.split(' ')
    res = [0]
    for token in formula:
      if token in vocab_to_idx:
        res.append( vocab_to_idx[token] + 4 )
      else:
        res.append(2)
    res.append(1)
    return res
formulas = list(map( formula_to_indices, formulas))

In [6]:
formulas

[[0,
  230,
  466,
  499,
  13,
  200,
  501,
  465,
  499,
  229,
  501,
  472,
  481,
  81,
  285,
  499,
  473,
  501,
  465,
  499,
  13,
  481,
  460,
  501,
  230,
  466,
  499,
  13,
  200,
  501,
  465,
  499,
  229,
  501,
  472,
  481,
  465,
  499,
  336,
  501,
  285,
  499,
  473,
  501,
  465,
  499,
  13,
  481,
  465,
  499,
  336,
  501,
  460,
  501,
  481,
  481,
  465,
  499,
  336,
  501,
  499,
  209,
  499,
  481,
  465,
  499,
  336,
  501,
  13,
  481,
  501,
  499,
  481,
  11,
  481,
  465,
  499,
  336,
  501,
  501,
  501,
  461,
  26,
  78,
  184,
  465,
  499,
  336,
  336,
  501,
  8,
  481,
  9,
  13,
  499,
  209,
  499,
  26,
  501,
  499,
  29,
  501,
  501,
  491,
  78,
  184,
  8,
  481,
  9,
  463,
  39,
  18,
  16,
  1],
 [0,
  472,
  490,
  465,
  499,
  25,
  501,
  39,
  8,
  24,
  13,
  499,
  209,
  499,
  488,
  470,
  485,
  490,
  420,
  501,
  499,
  489,
  501,
  501,
  9,
  465,
  499,
  209,
  499,
  25,
  501,
  499,
  24,
  11,
  12

Reading the files obtained after basic preprocessing

In [7]:
train = open('../input/taskset/train.lst').read().split('\n')[:-1]
val = open('../input/taskset/valid.lst').read().split('\n')[:-1]
test = open('../input/taskset/test.lst').read().split('\n')[:-1]    #reading files

In [8]:
import numpy as np
from PIL import Image

The images and their corresponding formulae indexes are now gather in variables train,Val,test

In [9]:
def import_images(datum):
    datum = datum.split(' ')
    img = np.array(Image.open('../input/processed-images/images_processed/'+datum[0]).convert('L'))
    return (img, formulas[ int(datum[1]) ])

train = list(map(import_images, train)) #reading the images and storing them
val = list(map(import_images, val))
test = list(map(import_images, test))

In [10]:
print(train[0])

(array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8), [0, 472, 490, 465, 499, 25, 501, 39, 8, 24, 13, 499, 209, 499, 488, 470, 485, 490, 420, 501, 499, 489, 501, 501, 9, 465, 499, 209, 499, 25, 501, 499, 24, 11, 125, 465, 499, 25, 501, 501, 501, 244, 472, 489, 465, 499, 25, 501, 11, 489, 465, 499, 25, 501, 472, 420, 465, 499, 25, 501, 11, 489, 465, 499, 25, 501, 490, 477, 484, 465, 499, 25, 501, 420, 472, 438, 465, 499, 25, 501, 348, 13, 499, 209, 499, 472, 491, 465, 499, 25, 501, 501, 499, 8, 24, 13, 499, 209, 499, 488, 470, 485, 490, 420, 501, 499, 489, 501, 501, 9, 465, 499, 209, 499, 25, 501, 499, 24, 11, 125, 465, 499, 25, 501, 501, 501, 501, 501, 78, 16, 1])


In [11]:
shapes_list=[]
for i in range(0,len(train)):
    shapes_list.append(train[i][0].shape)

In [12]:
uni_shapes_list=list(set(shapes_list))
print(uni_shapes_list)

[(50, 320), (40, 280), (100, 360), (50, 120), (50, 280), (40, 160), (40, 320), (50, 360), (60, 360), (50, 400), (50, 240), (40, 360), (40, 200), (160, 400), (50, 200), (100, 500), (40, 240)]


For the sake of ease we are consedering images of size 50,320 for training and the data is further preprocessed into X and y,these are used for training. 

In [13]:
X_train=[]
y_train=[]                                        #arranging the data into X_train(images) and y_train(formula indices)
for i in range(0,len(train)):
    if(train[i][0].shape==(50, 320)):
        X_train.append(train[i][0])
        y_train.append(np.array(train[i][1]))

In [14]:
X_val=[]
y_val=[]
for i in range(0,len(val)):
    if(val[i][0].shape==(50, 320)):
        X_val.append(val[i][0])
        y_val.append(np.array(val[i][1]))

In [15]:
X_train=np.array(X_train)
y_train=np.array(y_train)

In [16]:
X_valid=np.array(X_val)
y_valid=np.array(y_val)

In [17]:
print(X_train.shape)
print(y_train.shape)

(3805, 50, 320)
(3805,)


In [18]:
print(X_valid.shape)
print(y_valid.shape)

(423, 50, 320)
(423,)


In [19]:
y_train[0].size

74

In [20]:
y_valid[0].size

78

In [21]:
size_y_train=[]
for i in range(0,len(y_train)):
    size_y_train.append(y_train[i].size)

In [22]:
size_y_valid=[]
for i in range(0,len(y_valid)):
    size_y_valid.append(y_valid[i].size)

In [23]:
max_size=158

In [24]:
#TODO :add for loop
for i in range(0,len(y_train)):                     # padding the sequences and making them into a constant length
    tmp=y_train[i]
    pad=np.pad(tmp,(0, max_size - tmp.size), 'constant', constant_values = 3)
    y_train[i]=np.expand_dims( pad, 0)

In [25]:
for i in range(0,len(y_valid)):
    tmp=y_valid[i]
    pad=np.pad(tmp,(0, max_size - tmp.size), 'constant', constant_values = 3)
    y_valid[i]=np.expand_dims( pad, 0)

In [26]:
print(y_train[0].size)
print(y_train[0])

158
[[  0 341   8 211   9  39 316 499 473 496 486 501 499  13   8 499 417 499
  209 499 475 465 499  25 501 501 499  25 501 501 501   9 230 466 499 211
  501 472 497 465 499 468 501 230 466 499 211 501 472 497 465 499 468 465
  499 336 501 501  46 466 499  24 501   8 497  13 497 465 499 336 501   9
  501   1   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3]]


In [27]:
print(y_valid[0].size)
print(y_valid[0])

158
[[  0 459 466 499 382 501   8 382   9  39  24  13 209 499 331 473 465 499
  382 501 501 499  26 501  11  33 331 473 465 499 382 501 407 466 499 484
   39  24 501 465 499 229 501 209 499 484 473 465 499  13  25 484 331 473
  465 499 382 501 501 501 499  24  13 473 465 499  13  25 484 331 473 465
  499 382 501 501 501   1   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3   3
    3   3   3   3   3   3   3   3   3   3   3   3   3   3]]


In [28]:
y_train=list(y_train)

In [29]:
y_valid=list(y_valid)

In [30]:
y_train[0]

array([[  0, 341,   8, 211,   9,  39, 316, 499, 473, 496, 486, 501, 499,
         13,   8, 499, 417, 499, 209, 499, 475, 465, 499,  25, 501, 501,
        499,  25, 501, 501, 501,   9, 230, 466, 499, 211, 501, 472, 497,
        465, 499, 468, 501, 230, 466, 499, 211, 501, 472, 497, 465, 499,
        468, 465, 499, 336, 501, 501,  46, 466, 499,  24, 501,   8, 497,
         13, 497, 465, 499, 336, 501,   9, 501,   1,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3]])

In [31]:
y_valid[0]

array([[  0, 459, 466, 499, 382, 501,   8, 382,   9,  39,  24,  13, 209,
        499, 331, 473, 465, 499, 382, 501, 501, 499,  26, 501,  11,  33,
        331, 473, 465, 499, 382, 501, 407, 466, 499, 484,  39,  24, 501,
        465, 499, 229, 501, 209, 499, 484, 473, 465, 499,  13,  25, 484,
        331, 473, 465, 499, 382, 501, 501, 501, 499,  24,  13, 473, 465,
        499,  13,  25, 484, 331, 473, 465, 499, 382, 501, 501, 501,   1,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
          3,   3]])

In [32]:
for i in range(0,len(y_train)):
     y_train[i]=y_train[i][0]

In [33]:
for i in range(0,len(y_valid)):
     y_valid[i]=y_valid[i][0]

In [34]:
y_train[0]

array([  0, 341,   8, 211,   9,  39, 316, 499, 473, 496, 486, 501, 499,
        13,   8, 499, 417, 499, 209, 499, 475, 465, 499,  25, 501, 501,
       499,  25, 501, 501, 501,   9, 230, 466, 499, 211, 501, 472, 497,
       465, 499, 468, 501, 230, 466, 499, 211, 501, 472, 497, 465, 499,
       468, 465, 499, 336, 501, 501,  46, 466, 499,  24, 501,   8, 497,
        13, 497, 465, 499, 336, 501,   9, 501,   1,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3])

In [35]:
y_valid[0]

array([  0, 459, 466, 499, 382, 501,   8, 382,   9,  39,  24,  13, 209,
       499, 331, 473, 465, 499, 382, 501, 501, 499,  26, 501,  11,  33,
       331, 473, 465, 499, 382, 501, 407, 466, 499, 484,  39,  24, 501,
       465, 499, 229, 501, 209, 499, 484, 473, 465, 499,  13,  25, 484,
       331, 473, 465, 499, 382, 501, 501, 501, 499,  24,  13, 473, 465,
       499,  13,  25, 484, 331, 473, 465, 499, 382, 501, 501, 501,   1,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,   3,
         3,   3])

In [36]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [37]:
X_train.shape

(3805, 50, 320)

In [38]:
X_valid.shape

(423, 50, 320)

In [39]:
y_train=np.array(y_train)
y_train.shape

(3805, 158)

In [40]:
y_valid=np.array(y_valid)
y_valid.shape

(423, 158)

Conversion of y to one-hot encoding

In [41]:
from keras.utils import to_categorical #one hot encoding 
y_train= to_categorical(y_train)

In [42]:
from keras.utils import to_categorical
y_valid= to_categorical(y_valid)

In [43]:
y_train.shape

(3805, 158, 503)

In [44]:
y_valid.shape

(423, 158, 503)

In [45]:
y_train[0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [46]:
y_valid[0]

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [47]:
X_train = X_train.reshape(X_train.shape[0],320,50,1) #imp step to reshape the arrays

In [48]:
X_valid= X_valid.reshape(X_valid.shape[0],320,50,1)

In [49]:
X_train.shape

(3805, 320, 50, 1)

In [50]:
X_valid.shape

(423, 320, 50, 1)

In [51]:
input_shape=(320,50,1)

Regularizing images

In [52]:
X_train = np.array(X_train, dtype=np.float)
X_train = X_train - 128.
X_train = X_train / 128.

In [53]:
X_valid = np.array(X_valid, dtype=np.float)
X_valid = X_valid - 128.
X_valid = X_valid / 128.

In [54]:
import tensorflow as tf
from keras import layers
from keras.layers import Input, Dense, Activation, ZeroPadding2D, BatchNormalization, Flatten, Conv2D ,Reshape,TimeDistributed,GRU
from keras.layers import AveragePooling2D,Concatenate, Add,MaxPooling2D, Dropout, GlobalMaxPooling2D,Flatten, GlobalAveragePooling2D,Bidirectional,LSTM
from keras.models import Model, Sequential

**Building the model**

Building the CNN

In [55]:
model = Sequential()
model.add(Conv2D(16, kernel_size=(3, 3),activation='relu',input_shape=(320,50,1)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))


In the original paper they built the CNN  model implemented from the (Xu et al. 2015) model
We can add multiple layers and can use max pooling layers.
The main idea of implementing a CNN is to learn image features which can be later passed down to LSTM layer

In [56]:
conv_to_rnn_dims = (158,736)

**Converting the CNN dimensions to suitable RNN dimensions**

In [57]:
model.add(Reshape(conv_to_rnn_dims))
model.add(Dense(128, activation='relu'))

adding the reshape layer is an important step as it involves CNN and LSTM connection
The dense layer used here is the Row Encoder which is similar to the Research paper

In [58]:
model.add(Bidirectional(LSTM(60 , return_sequences = True )))
model.add(Bidirectional(LSTM(60 , return_sequences = True )))
model.add(Dense(503, activation='relu'))

The above layers used are the Bi-directional LSTM which are some special type of RNN's.
We can add more LSTM layers which helps in better learning 

In [59]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 318, 48, 16)       160       
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 316, 46, 32)       4640      
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 158, 23, 32)       0         
_________________________________________________________________
reshape (Reshape)            (None, 158, 736)          0         
_________________________________________________________________
dense (Dense)                (None, 158, 128)          94336     
_________________________________________________________________
bidirectional (Bidirectional (None, 158, 120)          90720     
_________________________________________________________________
bidirectional_1 (Bidirection (None, 158, 120)          8

In [60]:
#from keras.optimizers import Adam
#add = Adam(learning_rate=0.1,
 #   beta_1=0.99,
  #  beta_2=0.998,
   # epsilon=1e-06,
    #amsgrad=False,)
#model.compile(loss = 'categorical_crossentropy' , optimizer = add )

In the research paper the and th github repo implemented both the optimizers

In [66]:
from keras.optimizers import SGD
opt = SGD(lr=0.01)
model.compile(loss = "categorical_crossentropy", optimizer = opt)

In [ ]:
hist = model.fit(X_train,y_train,epochs = 5,validation_data = (X_valid,y_valid),shuffle = False)

Epoch 1/5
119/119 [==============================] - 6s 49ms/step - loss: 3.2869 - val_loss: 3.2684
Epoch 2/5
119/119 [==============================] - 6s 47ms/step - loss: 3.2523 - val_loss: 3.2357
Epoch 3/5
119/119 [==============================] - 6s 48ms/step - loss: 3.2198 - val_loss: 3.2030
Epoch 4/5
119/119 [==============================] - 6s 47ms/step - loss: 3.1944 - val_loss: 3.1704
Epoch 5/5
118/119 [============================>.] - ETA: 0s - loss: 3.1461

As we can see that both the training set loss and the validation set loss has been decresing

The above model can be tested against the test set using model.predict()



# **Scope of improvement:**

The above model after training for some no.of epochs  and changing the no.of layers,adding dropouts,etc we can improve the model.
Even the preprocessing can be done in better way.